name:                artemis-ii
version:             0.1.0.0
github:              "as-capabl/artemis-ii"
license:             BSD3
author:              "Hidenori Azuma"
maintainer:          "as.capabl@gmail.com"
copyright:           "2019 Hidenori Azuma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/as-capabl/artemis-ii#readme>

dependencies:
- base >= 4.7 && < 5
- indexed

library:
  source-dirs: src

executables:
  artemis-ii-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - artemis-ii
    - rebindable
    - data-default

tests:
  artemis-ii-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - artemis-ii
